#ifndef WINTPROXY_CONSTANTS_H
#define WINTPROXY_CONSTANTS_H

#define WTP_TCP_RELAY_PORT             34010
#define WTP_UDP_RELAY_PORT             34011

#define WTP_DIVERT_WORKER_COUNT        4
#define WTP_DIVERT_MAX_PACKET_SIZE     65535
#define WTP_DIVERT_QUEUE_LENGTH        16384
#define WTP_DIVERT_QUEUE_TIME_MS       100
#define WTP_DIVERT_QUEUE_SIZE          33554432U

#define WTP_DNS_NAT_BUCKETS            256
#define WTP_DNS_NAT_POOL_SIZE          4096
#define WTP_DNS_NAT_TTL_MS             30000
#define WTP_DNS_FORWARD_BUFFER_SIZE    2048

#define WTP_CONNTRACK_BUCKETS          16384
#define WTP_CONNTRACK_POOL_SIZE        65536
#define WTP_CONNTRACK_TTL_SEC          60
#define WTP_CONNTRACK_CLEANUP_SEC      30

#define WTP_PROC_FLOW_BUCKETS          8192
#define WTP_PROC_FLOW_POOL_SIZE        65536
#define WTP_PROC_PID_BUCKETS           2048
#define WTP_PROC_PID_POOL_SIZE         8192
#define WTP_PROC_INDEX_REFRESH_MS      500
#define WTP_PROC_MISS_REFRESH_MIN_MS   10
#define WTP_PROC_CACHE_TTL_MS          5000

#define WTP_UDP_SESSION_MAX            256
#define WTP_UDP_SESSION_BUCKETS        512
#define WTP_UDP_SESSION_TTL_SEC        300
#define WTP_UDP_RETRY_DELAY_MS         5000
#define WTP_UDP_BUFFER_SIZE            65536

#define WTP_TCP_RELAY_WORKER_MAX       32
#define WTP_TCP_RELAY_CONN_MAX         8192
#define WTP_TCP_RELAY_BUFFER_SIZE      32768
#define WTP_TCP_MSS_CLAMP              1360
#define WTP_TCP_RELAY_SRC_PORT_MIN     40000
#define WTP_TCP_RELAY_SRC_PORT_MAX     60999

#define WTP_IPV4_LOOPBACK              0x0100007FU

#endif
